// Generated by `wit-bindgen` 0.34.0. DO NOT EDIT!
// <auto-generated />
#nullable enable

using System;
using System.Runtime.CompilerServices;
using System.Collections;
using System.Runtime.InteropServices;
using System.Text;
using System.Collections.Generic;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;

namespace ExampleWorld;

public partial class ExampleWorldImpl {
    
    [UnmanagedCallersOnly(EntryPoint = "add")]
    public static unsafe int wasmExportAdd(int p0, int p1) {
        return p0 +p1;
    }
}
